Traceback (most recent call last):
  File "H:\HadiSadoghiYazdi\Circuit\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
    ~~~~~~~~~^
        nb,
        ^^^
    ...<4 lines>...
        **kwargs,
        ^^^^^^^^^
    )
    ^
  File "H:\HadiSadoghiYazdi\Circuit\Lib\site-packages\nbclient\client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "H:\HadiSadoghiYazdi\Circuit\Lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Program Files\Python313\Lib\asyncio\base_events.py", line 721, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "H:\HadiSadoghiYazdi\Circuit\Lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
        cell, index, execution_count=self.code_cells_executed + 1
    )
  File "H:\HadiSadoghiYazdi\Circuit\Lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "H:\HadiSadoghiYazdi\Circuit\Lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import numpy as np
import matplotlib.pyplot as plt

import PySpice.Logging.Logging as Logging
logger = Logging.setup_logging()
from PySpice.Spice.Netlist import Circuit
from PySpice.Unit import #

# Define sweep parameters
Vinput_start = 0
Vinput_stop = 60
Vinput_step = 0.01

# Define the circuit
circuit = Circuit('First Example Define diode')

# Add a diode with specific parameters
circuit.D('1', '3', circuit.gnd, model='Diode')
circuit.model('Diode', 'D', IS=0.0000000001, rs=0.0341512, nd=2, eg=1.05743, xti=5, bv=1000, ibv=5e-08, cjo=10, vj=0.7, m=0.5, fc=0.5, tt=1e-07, kf=0, af=1)

# Add voltage source, resistors, and current source
circuit.V('input', '1', circuit.gnd, 5)
circuit.R('s', '2', '3', 0.356)
circuit.R('sh', '3', circuit.gnd, 312.55)
circuit.I('pv', '3', circuit.gnd, 8.17)
circuit.V('meas', '1', '2', 0)

# Create a simulator
simulator = circuit.simulator(temperature=25, nominal_temperature=25)

# Perform a DC sweep analysis
analysis = simulator.dc(Vinput=slice(Vinput_start, Vinput_stop, Vinput_step))

# Extract the data for node '3'
waveform = analysis['3']
sweep_values1=analysis['v-sweep']
InputCurrentMeasurement=analysis['vmeas']
# Assuming waveform.data provides the voltage values for node '3'
voltage_values = np.array(waveform)


# Plot the results
plt.plot(sweep_values1, voltage_values)
plt.xlabel('Vinput (V)')
plt.ylabel('Voltage at Node 3 (V)')
plt.title('DC Sweep Analysis for Node 3')
plt.grid(True)
plt.show()

plt.plot(sweep_values1,InputCurrentMeasurement)
plt.xlabel('Vinput (V)')
plt.ylabel('Input current (A)')
plt.title('DC Sweep Analysis for input Node current')
plt.grid(True)
plt.show()

print(analysis.nodes)
------------------


[1;36m  Cell [1;32mIn[3], line 7[1;36m[0m
[1;33m    from PySpice.Unit import #[0m
[1;37m                             ^[0m
[1;31mSyntaxError[0m[1;31m:[0m Expected one or more names after 'import'


