Traceback (most recent call last):
  File "E:\MainHomePage\.M_HomePage\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "E:\MainHomePage\.M_HomePage\Lib\site-packages\nbclient\client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\MainHomePage\.M_HomePage\Lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dr\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "E:\MainHomePage\.M_HomePage\Lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "E:\MainHomePage\.M_HomePage\Lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "E:\MainHomePage\.M_HomePage\Lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import schemdraw
import schemdraw.elements as elm

with schemdraw.Drawing() as d:
    
    d += elm.SourceV().down().label('V1').at([0, 0])  # Add the voltage source V1
    
    d += elm.Ground().label('GND',loc='right').at([0, -3]) # Add the ground symbol for V1
    
    d += elm.Dot().label('N_in', loc='left').at([0,1]) # Add the node for N_in
    
    d += elm.Resistor().right().label('R1').at([0,1]) # Add resistor R1
    
    d += elm.Dot().label('N_out', loc='right') # Add the node for N_out
    
    d += elm.Diode().down().label('D1') # Add the diode D1
    
    d += elm.Ground().label('GND', loc='right') # Add the ground for the diode
    
    d += elm.Line().up().at([0, 0]).length(1) # Draw the connection between the voltage source and the resistor


------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [1;32mIn[1], line 1[0m
[1;32m----> 1[0m [38;5;28;01mimport[39;00m [38;5;21;01mschemdraw[39;00m
[0;32m      2[0m [38;5;28;01mimport[39;00m [38;5;21;01mschemdraw[39;00m[38;5;21;01m.[39;00m[38;5;21;01melements[39;00m [38;5;28;01mas[39;00m [38;5;21;01melm[39;00m
[0;32m      4[0m [38;5;28;01mwith[39;00m schemdraw[38;5;241m.[39mDrawing() [38;5;28;01mas[39;00m d:

[1;31mModuleNotFoundError[0m: No module named 'schemdraw'

